package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTGpdbRecord was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTGpdbRecord extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String GPDB_ITEM_ID_PROPERTY = "gpdbItemId";
    public static final String RECORD_NO_PROPERTY = "recordNo";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String VALUE_PROPERTY = "value";
    public static final String EIP_TGPDB_RECORD_FILE_PROPERTY = "eipTGpdbRecordFile";
    public static final String GPDB_PROPERTY = "gpdb";
    public static final String GPDB_ITEM_PROPERTY = "gpdbItem";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String GPDB_RECORD_ID_PK_COLUMN = "GPDB_RECORD_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setGpdbItemId(Integer gpdbItemId) {
        writeProperty("gpdbItemId", gpdbItemId);
    }
    public Integer getGpdbItemId() {
        return (Integer)readProperty("gpdbItemId");
    }
    
    
    public void setRecordNo(Integer recordNo) {
        writeProperty("recordNo", recordNo);
    }
    public Integer getRecordNo() {
        return (Integer)readProperty("recordNo");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }
    
    
    public void addToEipTGpdbRecordFile(com.aimluck.eip.cayenne.om.portlet.EipTGpdbRecordFile obj) {
        addToManyTarget("eipTGpdbRecordFile", obj, true);
    }
    public void removeFromEipTGpdbRecordFile(com.aimluck.eip.cayenne.om.portlet.EipTGpdbRecordFile obj) {
        removeToManyTarget("eipTGpdbRecordFile", obj, true);
    }
    public List getEipTGpdbRecordFile() {
        return (List)readProperty("eipTGpdbRecordFile");
    }
    
    
    public void setGpdb(com.aimluck.eip.cayenne.om.portlet.EipTGpdb gpdb) {
        setToOneTarget("gpdb", gpdb, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTGpdb getGpdb() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTGpdb)readProperty("gpdb");
    } 
    
    
    public void setGpdbItem(com.aimluck.eip.cayenne.om.portlet.EipTGpdbItem gpdbItem) {
        setToOneTarget("gpdbItem", gpdbItem, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTGpdbItem getGpdbItem() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTGpdbItem)readProperty("gpdbItem");
    } 
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
