package com.aimluck.eip.cayenne.om.account.auto;

/**
 * Class _EipMUserHoliday was generated by Cayenne. It is probably a good idea
 * to avoid changing this class manually, since it may be overwritten next time
 * code is regenerated. If you need to make any customizations, please use
 * subclass.
 */
public class _EipMUserHoliday extends org.apache.cayenne.CayenneDataObject {

  public static final String CREATE_USER_ID_PROPERTY = "createUserId";

  public static final String HOLIDAY_DATE_PROPERTY = "holidayDate";

  public static final String HOLIDAY_TITLE_PROPERTY = "holidayTitle";

  public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";

  public static final String TURBINE_USER_PROPERTY = "turbineUser";

  public static final String HOLIDAY_ID_PK_COLUMN = "HOLIDAY_ID";

  public void setCreateUserId(Integer create_user_id) {
    writeProperty("createUserId", create_user_id);
  }

  public Integer getCreateUserId() {
    return (Integer) readProperty("createUserId");
  }

  public void setHolidayDate(java.util.Date holidayDate) {
    writeProperty("holidayDate", holidayDate);
  }

  public java.util.Date getHolidayDate() {
    return (java.util.Date) readProperty("holidayDate");
  }

  public void setHolidayTitle(String holidayTitle) {
    writeProperty("holidayTitle", holidayTitle);
  }

  public String getHolidayTitle() {
    return (String) readProperty("holidayTitle");
  }

  public void setUpdateUserId(Integer update_user_id) {
    writeProperty("updateUserId", update_user_id);
  }

  public Integer getUpdateUserId() {
    return (Integer) readProperty("updateUserId");
  }

  public void setTurbineUser(
      com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
    setToOneTarget("turbineUser", turbineUser, true);
  }

  public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
    return (com.aimluck.eip.cayenne.om.security.TurbineUser) readProperty("turbineUser");
  }

}
