/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2010 Aimluck,Inc.
 * http://aipostyle.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTCabinetFolderMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTCabinetFolderMap extends org.apache.cayenne.CayenneDataObject {

    public static final String STATUS_PROPERTY = "status";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TCABINET_FOLDER_PROPERTY = "eipTCabinetFolder";

    public static final String ID_PK_COLUMN = "ID";

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTCabinetFolder(com.aimluck.eip.cayenne.om.portlet.EipTCabinetFolder eipTCabinetFolder) {
        setToOneTarget("eipTCabinetFolder", eipTCabinetFolder, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTCabinetFolder getEipTCabinetFolder() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTCabinetFolder)readProperty("eipTCabinetFolder");
    } 
    
    
}
