package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTProject was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTProject extends org.apache.cayenne.CayenneDataObject {

    public static final String ADMIN_USER_ID_PROPERTY = "adminUserId";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String EXPLANATION_PROPERTY = "explanation";
    public static final String PROGRESS_FLG_PROPERTY = "progressFlg";
    public static final String PROGRESS_RATE_PROPERTY = "progressRate";
    public static final String PROJECT_NAME_PROPERTY = "projectName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String EIP_TPROJECT_FILES_PROPERTY = "eipTProjectFiles";
    public static final String EIP_TPROJECT_MEMBER_PROPERTY = "eipTProjectMember";
    public static final String EIP_TPROJECT_TASK_PROPERTY = "eipTProjectTask";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String PROJECT_ID_PK_COLUMN = "PROJECT_ID";

    public void setAdminUserId(Integer adminUserId) {
        writeProperty("adminUserId", adminUserId);
    }
    public Integer getAdminUserId() {
        return (Integer)readProperty("adminUserId");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setExplanation(String explanation) {
        writeProperty("explanation", explanation);
    }
    public String getExplanation() {
        return (String)readProperty("explanation");
    }
    
    
    public void setProgressFlg(String progressFlg) {
        writeProperty("progressFlg", progressFlg);
    }
    public String getProgressFlg() {
        return (String)readProperty("progressFlg");
    }
    
    
    public void setProgressRate(Integer progressRate) {
        writeProperty("progressRate", progressRate);
    }
    public Integer getProgressRate() {
        return (Integer)readProperty("progressRate");
    }
    
    
    public void setProjectName(String projectName) {
        writeProperty("projectName", projectName);
    }
    public String getProjectName() {
        return (String)readProperty("projectName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void addToEipTProjectFiles(com.aimluck.eip.cayenne.om.portlet.EipTProjectFile obj) {
        addToManyTarget("eipTProjectFiles", obj, true);
    }
    public void removeFromEipTProjectFiles(com.aimluck.eip.cayenne.om.portlet.EipTProjectFile obj) {
        removeToManyTarget("eipTProjectFiles", obj, true);
    }
    public List getEipTProjectFiles() {
        return (List)readProperty("eipTProjectFiles");
    }
    
    
    public void addToEipTProjectMember(com.aimluck.eip.cayenne.om.portlet.EipTProjectMember obj) {
        addToManyTarget("eipTProjectMember", obj, true);
    }
    public void removeFromEipTProjectMember(com.aimluck.eip.cayenne.om.portlet.EipTProjectMember obj) {
        removeToManyTarget("eipTProjectMember", obj, true);
    }
    public List getEipTProjectMember() {
        return (List)readProperty("eipTProjectMember");
    }
    
    
    public void addToEipTProjectTask(com.aimluck.eip.cayenne.om.portlet.EipTProjectTask obj) {
        addToManyTarget("eipTProjectTask", obj, true);
    }
    public void removeFromEipTProjectTask(com.aimluck.eip.cayenne.om.portlet.EipTProjectTask obj) {
        removeToManyTarget("eipTProjectTask", obj, true);
    }
    public List getEipTProjectTask() {
        return (List)readProperty("eipTProjectTask");
    }
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
