package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTProjectTaskComment was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTProjectTaskComment extends org.apache.cayenne.CayenneDataObject {

    public static final String COMMENT_PROPERTY = "comment";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String TASK_ID_PROPERTY = "taskId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TPROJECT_TASK_PROPERTY = "eipTProjectTask";
    public static final String EIP_TPROJECT_TASK_COMMENT_FILE_PROPERTY = "eipTProjectTaskCommentFile";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String COMMENT_ID_PK_COLUMN = "COMMENT_ID";

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setTaskId(Integer taskId) {
        writeProperty("taskId", taskId);
    }
    public Integer getTaskId() {
        return (Integer)readProperty("taskId");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setEipTProjectTask(com.aimluck.eip.cayenne.om.portlet.EipTProjectTask eipTProjectTask) {
        setToOneTarget("eipTProjectTask", eipTProjectTask, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTProjectTask getEipTProjectTask() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTProjectTask)readProperty("eipTProjectTask");
    } 
    
    
    public void addToEipTProjectTaskCommentFile(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskCommentFile obj) {
        addToManyTarget("eipTProjectTaskCommentFile", obj, true);
    }
    public void removeFromEipTProjectTaskCommentFile(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskCommentFile obj) {
        removeToManyTarget("eipTProjectTaskCommentFile", obj, true);
    }
    public List getEipTProjectTaskCommentFile() {
        return (List)readProperty("eipTProjectTaskCommentFile");
    }
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
