package com.aimluck.eip.cayenne.om.portlet.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aimluck.eip.cayenne.om.portlet.EipTTimeline;
import com.aimluck.eip.cayenne.om.security.TurbineUser;

/**
 * Class _EipTTimelineLike was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTTimelineLike extends CayenneDataObject {

    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String TIMELINE_ID_PROPERTY = "timelineId";
    public static final String EIP_TTIMELINE_PROPERTY = "eipTTimeline";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String TIMELINE_LIKE_ID_PK_COLUMN = "TIMELINE_LIKE_ID";

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setTimelineId(Integer timelineId) {
        writeProperty("timelineId", timelineId);
    }
    public Integer getTimelineId() {
        return (Integer)readProperty("timelineId");
    }

    public void setEipTTimeline(EipTTimeline eipTTimeline) {
        setToOneTarget("eipTTimeline", eipTTimeline, true);
    }

    public EipTTimeline getEipTTimeline() {
        return (EipTTimeline)readProperty("eipTTimeline");
    }


    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
