package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/**
 * Class _EipMFacilityGroup was generated by Cayenne. It is probably a good idea
 * to avoid changing this class manually, since it may be overwritten next time
 * code is regenerated. If you need to make any customizations, please use
 * subclass.
 */
public class _EipMFacilityGroup extends org.apache.cayenne.CayenneDataObject {

  public static final String GROUP_NAME_PROPERTY = "groupName";

  public static final String SORT_PROPERTY = "sort";

  public static final String EIP_MFACILITY_GROUP_PROPERTY = "eipMFacilityGroup";

  public static final String CREATE_DATE_PROPERTY = "createDate";

  public static final String UPDATE_DATE_PROPERTY = "updateDate";

  public static final String GROUP_ID_PK_COLUMN = "GROUP_ID";

  public void setGroupName(String groupName) {
    writeProperty("groupName", groupName);
  }

  public String getGroupName() {
    return (String) readProperty("groupName");
  }

  public void setCreateDate(java.util.Date createDate) {
    writeProperty("createDate", createDate);
  }

  public java.util.Date getCreateDate() {
    return (java.util.Date) readProperty("createDate");
  }

  public void setUpdateDate(java.util.Date updateDate) {
    writeProperty("updateDate", updateDate);
  }

  public java.util.Date getUpdateDate() {
    return (java.util.Date) readProperty("updateDate");
  }

  public void setSort(Integer sort) {
    writeProperty("sort", sort);
  }

  public Integer getSort() {
    return (Integer) readProperty("sort");
  }

  public void addToEipMFacilityGroup(
      com.aimluck.eip.cayenne.om.portlet.EipMFacilityGroupMap obj) {
    addToManyTarget("eipMFacilityGroup", obj, true);
  }

  public void removeFromEipMFacilityGroup(
      com.aimluck.eip.cayenne.om.portlet.EipMFacilityGroupMap obj) {
    removeToManyTarget("eipMFacilityGroup", obj, true);
  }

  public List getEipMFacilityGroup() {
    return (List) readProperty("eipMFacilityGroup");
  }

}
