package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTSurveyResponseMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTSurveyResponseMap extends org.apache.cayenne.CayenneDataObject {

    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TSURVEY_PROPERTY = "eipTSurvey";
    public static final String EIP_TSURVEY_OPTION_PROPERTY = "eipTSurveyOption";

    public static final String RESPONSE_ID_PK_COLUMN = "RESPONSE_ID";

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTSurvey(com.aimluck.eip.cayenne.om.portlet.EipTSurvey eipTSurvey) {
        setToOneTarget("eipTSurvey", eipTSurvey, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTSurvey getEipTSurvey() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTSurvey)readProperty("eipTSurvey");
    } 
    
    
    public void setEipTSurveyOption(com.aimluck.eip.cayenne.om.portlet.EipTSurveyOption eipTSurveyOption) {
        setToOneTarget("eipTSurveyOption", eipTSurveyOption, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTSurveyOption getEipTSurveyOption() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTSurveyOption)readProperty("eipTSurveyOption");
    } 
    
    
}
