package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTWikiCategory was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTWikiCategory extends org.apache.cayenne.CayenneDataObject {

    public static final String CATEGORY_NAME_PROPERTY = "categoryName";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TWIKI_PROPERTY = "eipTWiki";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String CATEGORY_ID_PK_COLUMN = "CATEGORY_ID";

    public void setCategoryName(String categoryName) {
        writeProperty("categoryName", categoryName);
    }
    public String getCategoryName() {
        return (String)readProperty("categoryName");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void addToEipTWiki(com.aimluck.eip.cayenne.om.portlet.EipTWiki obj) {
        addToManyTarget("eipTWiki", obj, true);
    }
    public void removeFromEipTWiki(com.aimluck.eip.cayenne.om.portlet.EipTWiki obj) {
        removeToManyTarget("eipTWiki", obj, true);
    }
    public List getEipTWiki() {
        return (List)readProperty("eipTWiki");
    }
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
