package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipMHoliday was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipMHoliday extends org.apache.cayenne.CayenneDataObject {

    public static final String DEFAULT_FLAG_PROPERTY = "defaultFlag";
    public static final String HOLIDAY_DATE_PROPERTY = "holidayDate";
    public static final String HOLIDAY_NAME_PROPERTY = "holidayName";

    public static final String HOLIDAY_ID_PK_COLUMN = "holiday_id";

    public void setDefaultFlag(String defaultFlag) {
        writeProperty("defaultFlag", defaultFlag);
    }
    public String getDefaultFlag() {
        return (String)readProperty("defaultFlag");
    }
    
    
    public void setHolidayDate(java.util.Date holidayDate) {
        writeProperty("holidayDate", holidayDate);
    }
    public java.util.Date getHolidayDate() {
        return (java.util.Date)readProperty("holidayDate");
    }
    
    
    public void setHolidayName(String holidayName) {
        writeProperty("holidayName", holidayName);
    }
    public String getHolidayName() {
        return (String)readProperty("holidayName");
    }
    
    
}
