package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipMGpdbKubunValue was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipMGpdbKubunValue extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String GPDB_KUBUN_ID_PROPERTY = "gpdbKubunId";
    public static final String GPDB_KUBUN_VALUE_PROPERTY = "gpdbKubunValue";
    public static final String ORDER_NO_PROPERTY = "orderNo";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String GPDB_KUBUN_PROPERTY = "gpdbKubun";

    public static final String GPDB_KUBUN_VALUE_ID_PK_COLUMN = "GPDB_KUBUN_VALUE_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setGpdbKubunId(Integer gpdbKubunId) {
        writeProperty("gpdbKubunId", gpdbKubunId);
    }
    public Integer getGpdbKubunId() {
        return (Integer)readProperty("gpdbKubunId");
    }
    
    
    public void setGpdbKubunValue(String gpdbKubunValue) {
        writeProperty("gpdbKubunValue", gpdbKubunValue);
    }
    public String getGpdbKubunValue() {
        return (String)readProperty("gpdbKubunValue");
    }
    
    
    public void setOrderNo(Integer orderNo) {
        writeProperty("orderNo", orderNo);
    }
    public Integer getOrderNo() {
        return (Integer)readProperty("orderNo");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setGpdbKubun(com.aimluck.eip.cayenne.om.portlet.EipMGpdbKubun gpdbKubun) {
        setToOneTarget("gpdbKubun", gpdbKubun, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipMGpdbKubun getGpdbKubun() {
        return (com.aimluck.eip.cayenne.om.portlet.EipMGpdbKubun)readProperty("gpdbKubun");
    } 
    
    
}
