package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTMessage was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMessage extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String MEMBER_COUNT_PROPERTY = "memberCount";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TMESSAGE_FILES_PROPERTY = "eipTMessageFiles";
    public static final String EIP_TMESSAGE_READ_PROPERTY = "eipTMessageRead";
    public static final String EIP_TMESSAGE_ROOM_PROPERTY = "eipTMessageRoom";

    public static final String MESSAGE_ID_PK_COLUMN = "MESSAGE_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setMemberCount(Integer memberCount) {
        writeProperty("memberCount", memberCount);
    }
    public Integer getMemberCount() {
        return (Integer)readProperty("memberCount");
    }
    
    
    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void addToEipTMessageFiles(com.aimluck.eip.cayenne.om.portlet.EipTMessageFile obj) {
        addToManyTarget("eipTMessageFiles", obj, true);
    }
    public void removeFromEipTMessageFiles(com.aimluck.eip.cayenne.om.portlet.EipTMessageFile obj) {
        removeToManyTarget("eipTMessageFiles", obj, true);
    }
    public List getEipTMessageFiles() {
        return (List)readProperty("eipTMessageFiles");
    }
    
    
    public void addToEipTMessageRead(com.aimluck.eip.cayenne.om.portlet.EipTMessageRead obj) {
        addToManyTarget("eipTMessageRead", obj, true);
    }
    public void removeFromEipTMessageRead(com.aimluck.eip.cayenne.om.portlet.EipTMessageRead obj) {
        removeToManyTarget("eipTMessageRead", obj, true);
    }
    public List getEipTMessageRead() {
        return (List)readProperty("eipTMessageRead");
    }
    
    
    public void setEipTMessageRoom(com.aimluck.eip.cayenne.om.portlet.EipTMessageRoom eipTMessageRoom) {
        setToOneTarget("eipTMessageRoom", eipTMessageRoom, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTMessageRoom getEipTMessageRoom() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTMessageRoom)readProperty("eipTMessageRoom");
    } 
    
    
}
