package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipMGpdbKubun was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipMGpdbKubun extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String GPDB_KUBUN_NAME_PROPERTY = "gpdbKubunName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_MGPDB_KUBUN_PROPERTY = "eipMGpdbKubun";

    public static final String GPDB_KUBUN_ID_PK_COLUMN = "GPDB_KUBUN_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setGpdbKubunName(String gpdbKubunName) {
        writeProperty("gpdbKubunName", gpdbKubunName);
    }
    public String getGpdbKubunName() {
        return (String)readProperty("gpdbKubunName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void addToEipMGpdbKubun(com.aimluck.eip.cayenne.om.portlet.EipMGpdbKubunValue obj) {
        addToManyTarget("eipMGpdbKubun", obj, true);
    }
    public void removeFromEipMGpdbKubun(com.aimluck.eip.cayenne.om.portlet.EipMGpdbKubunValue obj) {
        removeToManyTarget("eipMGpdbKubun", obj, true);
    }
    public List getEipMGpdbKubun() {
        return (List)readProperty("eipMGpdbKubun");
    }
    
    
}
