package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTScheduleFile was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTScheduleFile extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FILE_NAME_PROPERTY = "fileName";
    public static final String FILE_PATH_PROPERTY = "filePath";
    public static final String FILE_THUMBNAIL_PROPERTY = "fileThumbnail";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String SCHEDULE_ID_PROPERTY = "scheduleId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TSCHEDULE_PROPERTY = "eipTSchedule";

    public static final String FILE_ID_PK_COLUMN = "FILE_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setFileName(String fileName) {
        writeProperty("fileName", fileName);
    }
    public String getFileName() {
        return (String)readProperty("fileName");
    }
    
    
    public void setFilePath(String filePath) {
        writeProperty("filePath", filePath);
    }
    public String getFilePath() {
        return (String)readProperty("filePath");
    }
    
    
    public void setFileThumbnail(byte[] fileThumbnail) {
        writeProperty("fileThumbnail", fileThumbnail);
    }
    public byte[] getFileThumbnail() {
        return (byte[])readProperty("fileThumbnail");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setScheduleId(Integer scheduleId) {
        writeProperty("scheduleId", scheduleId);
    }
    public Integer getScheduleId() {
        return (Integer)readProperty("scheduleId");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setEipTSchedule(com.aimluck.eip.cayenne.om.portlet.EipTSchedule eipTSchedule) {
        setToOneTarget("eipTSchedule", eipTSchedule, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTSchedule getEipTSchedule() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTSchedule)readProperty("eipTSchedule");
    } 
    
    
}
