package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTGpdbItem was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTGpdbItem extends org.apache.cayenne.CayenneDataObject {

    public static final String ASC_DESC_PROPERTY = "ascDesc";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String DEFAULT_SORT_FLG_PROPERTY = "defaultSortFlg";
    public static final String DETAIL_FLG_PROPERTY = "detailFlg";
    public static final String GPDB_ITEM_NAME_PROPERTY = "gpdbItemName";
    public static final String GPDB_KUBUN_ID_PROPERTY = "gpdbKubunId";
    public static final String LINE_PROPERTY = "line";
    public static final String LIST_FLG_PROPERTY = "listFlg";
    public static final String ORDER_NO_PROPERTY = "orderNo";
    public static final String REQUIRED_FLG_PROPERTY = "requiredFlg";
    public static final String SIZE_COL_PROPERTY = "sizeCol";
    public static final String SIZE_ROW_PROPERTY = "sizeRow";
    public static final String TITLE_FLG_PROPERTY = "titleFlg";
    public static final String TYPE_PROPERTY = "type";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TGPDB_RECORD_PROPERTY = "eipTGpdbRecord";
    public static final String GPDB_PROPERTY = "gpdb";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String GPDB_ITEM_ID_PK_COLUMN = "GPDB_ITEM_ID";

    public void setAscDesc(String ascDesc) {
        writeProperty("ascDesc", ascDesc);
    }
    public String getAscDesc() {
        return (String)readProperty("ascDesc");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setDefaultSortFlg(String defaultSortFlg) {
        writeProperty("defaultSortFlg", defaultSortFlg);
    }
    public String getDefaultSortFlg() {
        return (String)readProperty("defaultSortFlg");
    }
    
    
    public void setDetailFlg(String detailFlg) {
        writeProperty("detailFlg", detailFlg);
    }
    public String getDetailFlg() {
        return (String)readProperty("detailFlg");
    }
    
    
    public void setGpdbItemName(String gpdbItemName) {
        writeProperty("gpdbItemName", gpdbItemName);
    }
    public String getGpdbItemName() {
        return (String)readProperty("gpdbItemName");
    }
    
    
    public void setGpdbKubunId(Integer gpdbKubunId) {
        writeProperty("gpdbKubunId", gpdbKubunId);
    }
    public Integer getGpdbKubunId() {
        return (Integer)readProperty("gpdbKubunId");
    }
    
    
    public void setLine(Integer line) {
        writeProperty("line", line);
    }
    public Integer getLine() {
        return (Integer)readProperty("line");
    }
    
    
    public void setListFlg(String listFlg) {
        writeProperty("listFlg", listFlg);
    }
    public String getListFlg() {
        return (String)readProperty("listFlg");
    }
    
    
    public void setOrderNo(Integer orderNo) {
        writeProperty("orderNo", orderNo);
    }
    public Integer getOrderNo() {
        return (Integer)readProperty("orderNo");
    }
    
    
    public void setRequiredFlg(String requiredFlg) {
        writeProperty("requiredFlg", requiredFlg);
    }
    public String getRequiredFlg() {
        return (String)readProperty("requiredFlg");
    }
    
    
    public void setSizeCol(Integer sizeCol) {
        writeProperty("sizeCol", sizeCol);
    }
    public Integer getSizeCol() {
        return (Integer)readProperty("sizeCol");
    }
    
    
    public void setSizeRow(Integer sizeRow) {
        writeProperty("sizeRow", sizeRow);
    }
    public Integer getSizeRow() {
        return (Integer)readProperty("sizeRow");
    }
    
    
    public void setTitleFlg(String titleFlg) {
        writeProperty("titleFlg", titleFlg);
    }
    public String getTitleFlg() {
        return (String)readProperty("titleFlg");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void addToEipTGpdbRecord(com.aimluck.eip.cayenne.om.portlet.EipTGpdbRecord obj) {
        addToManyTarget("eipTGpdbRecord", obj, true);
    }
    public void removeFromEipTGpdbRecord(com.aimluck.eip.cayenne.om.portlet.EipTGpdbRecord obj) {
        removeToManyTarget("eipTGpdbRecord", obj, true);
    }
    public List getEipTGpdbRecord() {
        return (List)readProperty("eipTGpdbRecord");
    }
    
    
    public void setGpdb(com.aimluck.eip.cayenne.om.portlet.EipTGpdb gpdb) {
        setToOneTarget("gpdb", gpdb, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTGpdb getGpdb() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTGpdb)readProperty("gpdb");
    } 
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
