package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTMessageRoomMember was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMessageRoomMember extends org.apache.cayenne.CayenneDataObject {

    public static final String ROOM_ID_PROPERTY = "roomId";
    public static final String TARGET_USER_ID_PROPERTY = "targetUserId";
    public static final String USER_ID_PROPERTY = "userId";

    public static final String ID_PK_COLUMN = "ID";

    public void setRoomId(Integer roomId) {
        writeProperty("roomId", roomId);
    }
    public Integer getRoomId() {
        return (Integer)readProperty("roomId");
    }
    
    
    public void setTargetUserId(Integer targetUserId) {
        writeProperty("targetUserId", targetUserId);
    }
    public Integer getTargetUserId() {
        return (Integer)readProperty("targetUserId");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
}
