package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTProjectTask was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTProjectTask extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String END_DATE_PROPERTY = "endDate";
    public static final String END_PLAN_DATE_PROPERTY = "endPlanDate";
    public static final String EXPLANATION_PROPERTY = "explanation";
    public static final String ORDER_NO_PROPERTY = "orderNo";
    public static final String PARENT_TASK_ID_PROPERTY = "parentTaskId";
    public static final String PLAN_WORKLOAD_PROPERTY = "planWorkload";
    public static final String PRIORITY_PROPERTY = "priority";
    public static final String PROGRESS_RATE_PROPERTY = "progressRate";
    public static final String PROJECT_ID_PROPERTY = "projectId";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String START_PLAN_DATE_PROPERTY = "startPlanDate";
    public static final String STATUS_PROPERTY = "status";
    public static final String TASK_NAME_PROPERTY = "taskName";
    public static final String TRACKER_PROPERTY = "tracker";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String EIP_TPROJECT_PROPERTY = "eipTProject";
    public static final String EIP_TPROJECT_TASK_COMMENT_PROPERTY = "eipTProjectTaskComment";
    public static final String EIP_TPROJECT_TASK_FILE_PROPERTY = "eipTProjectTaskFile";
    public static final String EIP_TPROJECT_TASK_MEMBER_PROPERTY = "eipTProjectTaskMember";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String TASK_ID_PK_COLUMN = "TASK_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setEndDate(java.util.Date endDate) {
        writeProperty("endDate", endDate);
    }
    public java.util.Date getEndDate() {
        return (java.util.Date)readProperty("endDate");
    }
    
    
    public void setEndPlanDate(java.util.Date endPlanDate) {
        writeProperty("endPlanDate", endPlanDate);
    }
    public java.util.Date getEndPlanDate() {
        return (java.util.Date)readProperty("endPlanDate");
    }
    
    
    public void setExplanation(String explanation) {
        writeProperty("explanation", explanation);
    }
    public String getExplanation() {
        return (String)readProperty("explanation");
    }
    
    
    public void setOrderNo(Integer orderNo) {
        writeProperty("orderNo", orderNo);
    }
    public Integer getOrderNo() {
        return (Integer)readProperty("orderNo");
    }
    
    
    public void setParentTaskId(Integer parentTaskId) {
        writeProperty("parentTaskId", parentTaskId);
    }
    public Integer getParentTaskId() {
        return (Integer)readProperty("parentTaskId");
    }
    
    
    public void setPlanWorkload(java.math.BigDecimal planWorkload) {
        writeProperty("planWorkload", planWorkload);
    }
    public java.math.BigDecimal getPlanWorkload() {
        return (java.math.BigDecimal)readProperty("planWorkload");
    }
    
    
    public void setPriority(String priority) {
        writeProperty("priority", priority);
    }
    public String getPriority() {
        return (String)readProperty("priority");
    }
    
    
    public void setProgressRate(Integer progressRate) {
        writeProperty("progressRate", progressRate);
    }
    public Integer getProgressRate() {
        return (Integer)readProperty("progressRate");
    }
    
    
    public void setProjectId(Integer projectId) {
        writeProperty("projectId", projectId);
    }
    public Integer getProjectId() {
        return (Integer)readProperty("projectId");
    }
    
    
    public void setStartDate(java.util.Date startDate) {
        writeProperty("startDate", startDate);
    }
    public java.util.Date getStartDate() {
        return (java.util.Date)readProperty("startDate");
    }
    
    
    public void setStartPlanDate(java.util.Date startPlanDate) {
        writeProperty("startPlanDate", startPlanDate);
    }
    public java.util.Date getStartPlanDate() {
        return (java.util.Date)readProperty("startPlanDate");
    }
    
    
    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
    public void setTaskName(String taskName) {
        writeProperty("taskName", taskName);
    }
    public String getTaskName() {
        return (String)readProperty("taskName");
    }
    
    
    public void setTracker(String tracker) {
        writeProperty("tracker", tracker);
    }
    public String getTracker() {
        return (String)readProperty("tracker");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void setEipTProject(com.aimluck.eip.cayenne.om.portlet.EipTProject eipTProject) {
        setToOneTarget("eipTProject", eipTProject, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTProject getEipTProject() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTProject)readProperty("eipTProject");
    } 
    
    
    public void addToEipTProjectTaskComment(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskComment obj) {
        addToManyTarget("eipTProjectTaskComment", obj, true);
    }
    public void removeFromEipTProjectTaskComment(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskComment obj) {
        removeToManyTarget("eipTProjectTaskComment", obj, true);
    }
    public List getEipTProjectTaskComment() {
        return (List)readProperty("eipTProjectTaskComment");
    }
    
    
    public void addToEipTProjectTaskFile(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskFile obj) {
        addToManyTarget("eipTProjectTaskFile", obj, true);
    }
    public void removeFromEipTProjectTaskFile(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskFile obj) {
        removeToManyTarget("eipTProjectTaskFile", obj, true);
    }
    public List getEipTProjectTaskFile() {
        return (List)readProperty("eipTProjectTaskFile");
    }
    
    
    public void addToEipTProjectTaskMember(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskMember obj) {
        addToManyTarget("eipTProjectTaskMember", obj, true);
    }
    public void removeFromEipTProjectTaskMember(com.aimluck.eip.cayenne.om.portlet.EipTProjectTaskMember obj) {
        removeToManyTarget("eipTProjectTaskMember", obj, true);
    }
    public List getEipTProjectTaskMember() {
        return (List)readProperty("eipTProjectTaskMember");
    }
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
