/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2008 Aimluck,Inc.
 * http://aipostyle.com/
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.aimluck.eip.cayenne.om.security.auto;

/** Class _TurbineRolePermission was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineRolePermission extends org.apache.cayenne.CayenneDataObject {

    public static final String TURBINE_PERMISSION_PROPERTY = "turbinePermission";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";

    public static final String PERMISSION_ID_PK_COLUMN = "PERMISSION_ID";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setTurbinePermission(com.aimluck.eip.cayenne.om.security.TurbinePermission turbinePermission) {
        setToOneTarget("turbinePermission", turbinePermission, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbinePermission getTurbinePermission() {
        return (com.aimluck.eip.cayenne.om.security.TurbinePermission)readProperty("turbinePermission");
    } 
    
    
    public void setTurbineRole(com.aimluck.eip.cayenne.om.security.TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineRole getTurbineRole() {
        return (com.aimluck.eip.cayenne.om.security.TurbineRole)readProperty("turbineRole");
    } 
    
    
}
