package org.apache.jetspeed.om.security.turbine;

import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jun 03 20:14:05 PDT 2002]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class TurbineGroup extends
    org.apache.jetspeed.om.security.turbine.BaseTurbineGroup implements
    Persistent, org.apache.jetspeed.om.security.Group {
  /**
   *
   */
  private static final long serialVersionUID = 7914289850313892511L;

  @Override
  public String getName() {
    return getGroupName();
  }

  @Override
  public void setName(String name) {
    setGroupName(name);
  }

  @Override
  public String getId() {
    return String.valueOf(this.getGroupId());
  }

  @Override
  public void setId(String id) {
  }
}
