package org.apache.jetspeed.om.security.turbine;

import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jun 03 20:14:05 PDT 2002]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class TurbinePermission extends
    org.apache.jetspeed.om.security.turbine.BaseTurbinePermission implements
    Persistent, org.apache.jetspeed.om.security.Permission {
  /**
   *
   */
  private static final long serialVersionUID = -2014230089921931316L;

  @Override
  public String getName() {
    return getPermissionName();
  }

  @Override
  public void setName(String name) {
    setPermissionName(name);
  }

  @Override
  public String getId() {
    return String.valueOf(this.getPermissionId());
  }

  @Override
  public void setId(String id) {
  }

}
