package org.apache.jetspeed.om.security.turbine;

import org.apache.torque.TorqueException;

/**
 * This class manages TurbineRole objects. The skeleton for this class was
 * autogenerated by Torque on:
 *
 * [Thu Jun 10 23:17:32 JST 2004]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public abstract class TurbineRoleManager extends BaseTurbineRoleManager {
  /**
   *
   */
  private static final long serialVersionUID = 8747088784238727546L;

  /**
   * Creates a new <code>TurbineRoleManager</code> instance.
   *
   * @exception TorqueException
   *              if an error occurs
   */
  public TurbineRoleManager() throws TorqueException {
    super();
  }
}
