ALTER TABLE EIP_T_ACL_PORTLET_FEATURE ALTER FEATURE_ALIAS_NAME TYPE VARCHAR(99)
;

ALTER TABLE EIP_T_ACL_PORTLET_FEATURE ALTER FEATURE_NAME TYPE VARCHAR(99)
;

ALTER TABLE EIP_T_MAIL_FILTER ALTER FILTER_NAME TYPE VARCHAR(255)
;

ALTER TABLE EIP_T_MAIL_FILTER ALTER FILTER_STRING TYPE VARCHAR(255)
;

ALTER TABLE EIP_T_MAIL_FOLDER ALTER FOLDER_NAME TYPE VARCHAR(128)
;

ALTER TABLE EIP_T_COMMON_CATEGORY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_SCHEDULE ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_TODO_CATEGORY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_TODO ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_M_MAIL_ACCOUNT ALTER SIGNATURE TYPE TEXT
;

ALTER TABLE EIP_T_MAIL ALTER SUBJECT TYPE TEXT
;

ALTER TABLE EIP_T_MAIL ALTER PERSON TYPE TEXT
;

ALTER TABLE EIP_T_MAIL ALTER FILE_PATH TYPE TEXT
;

ALTER TABLE EIP_M_ADDRESSBOOK ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_NOTE ALTER MESSAGE TYPE TEXT
;

ALTER TABLE EIP_T_MSGBOARD_CATEGORY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_MSGBOARD_TOPIC ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_MSGBOARD_FILE ALTER FILE_PATH TYPE TEXT
;

ALTER TABLE EIP_T_BLOG_THEMA ALTER DESCRIPTION TYPE TEXT
;

ALTER TABLE EIP_T_BLOG_ENTRY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_BLOG_COMMENT ALTER COMMENT TYPE TEXT
;

ALTER TABLE EIP_T_BLOG_FILE ALTER FILE_PATH TYPE TEXT
;

ALTER TABLE EIP_T_CABINET_FOLDER ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_CABINET_FILE ALTER FILE_PATH TYPE TEXT
;

ALTER TABLE EIP_T_CABINET_FILE ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_M_FACILITY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_M_FACILITY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_TIMECARD ALTER REASON TYPE TEXT
;

ALTER TABLE EIP_T_EXT_TIMECARD ALTER REASON TYPE TEXT
;

ALTER TABLE EIP_T_EXT_TIMECARD ALTER REMARKS TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_ROUTE ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_ROUTE ALTER ROUTE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_CATEGORY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_CATEGORY ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_CATEGORY ALTER TEMPLATE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_REQUEST ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_FILE ALTER FILE_PATH TYPE TEXT
;

ALTER TABLE EIP_T_WORKFLOW_REQUEST_MAP ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_MEMO ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_EVENTLOG ALTER IP_ADDR TYPE TEXT
;

ALTER TABLE EIP_T_EVENTLOG ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_ACL_ROLE ALTER NOTE TYPE TEXT
;

ALTER TABLE EIP_T_ACL_ROLE ALTER NOTE TYPE TEXT
;

CREATE TABLE application 
(
    ID serial, 
    APP_ID varchar(255) NULL, 
    CONSUMER_KEY varchar(99) NULL, 
    CONSUMER_SECRET varchar(99) NULL, 
    STATUS integer NULL, 
    TITLE varchar(99) NULL, 
    URL varchar(255) NULL, 
    SUMMARY varchar(255) NULL, 
    DESCRIPTION TEXT NULL, 
    CREATE_DATE DATE,
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

SELECT setval('application_id_seq',1);

CREATE TABLE oauth_consumer 
(
    ID serial, 
    APP_ID integer NULL,
    CONSUMER_KEY varchar(255) NULL, 
    CONSUMER_SECRET varchar(255) NULL, 
    NAME varchar(99) NULL, 
    TYPE varchar(99) NULL, 
    CREATE_DATE DATE,
    UPDATE_DATE TIMESTAMP,
    FOREIGN KEY (APP_ID) REFERENCES application (ID) ON DELETE CASCADE,
    PRIMARY KEY (ID)
);

SELECT setval('oauth_consumer_id_seq',1);

CREATE TABLE container_config 
(
    ID serial, 
    KEY varchar(64) NULL, 
    VALUE varchar(255) NULL, 
    PRIMARY KEY (ID)
);

SELECT setval('container_config_id_seq',1);

CREATE TABLE oauth_token 
(
    KEY integer NOT NULL, 
    ACCESS_TOKEN varchar(255) NULL, 
    TOKEN_SECRET varchar(255) NULL, 
    SESSION_HANDLE varchar(255) NULL, 
    TOKEN_EXPIRE_MILIS integer NULL,
    PRIMARY KEY (KEY)
);