--- modify table struct
ALTER TABLE EIP_T_SCHEDULE ADD MAIL_FLAG CHAR(1) ;

--- update data
UPDATE EIP_T_SCHEDULE SET MAIL_FLAG = 'A' ;
UPDATE EIP_M_ADDRESSBOOK_COMPANY SET COMPANY_NAME = '', COMPANY_NAME_KANA = '' WHERE COMPANY_ID = 1;
