package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipMProjectKubun was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipMProjectKubun extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String PROJECT_KUBUN_CD_PROPERTY = "projectKubunCd";
    public static final String PROJECT_KUBUN_NAME_PROPERTY = "projectKubunName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";

    public static final String PROJECT_KUBUN_ID_PK_COLUMN = "PROJECT_KUBUN_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setProjectKubunCd(String projectKubunCd) {
        writeProperty("projectKubunCd", projectKubunCd);
    }
    public String getProjectKubunCd() {
        return (String)readProperty("projectKubunCd");
    }
    
    
    public void setProjectKubunName(String projectKubunName) {
        writeProperty("projectKubunName", projectKubunName);
    }
    public String getProjectKubunName() {
        return (String)readProperty("projectKubunName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
}
