package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTProjectMember was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTProjectMember extends org.apache.cayenne.CayenneDataObject {

    public static final String PROJECT_ID_PROPERTY = "projectId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TPROJECT_PROPERTY = "eipTProject";

    public static final String ID_PK_COLUMN = "ID";

    public void setProjectId(Integer projectId) {
        writeProperty("projectId", projectId);
    }
    public Integer getProjectId() {
        return (Integer)readProperty("projectId");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTProject(com.aimluck.eip.cayenne.om.portlet.EipTProject eipTProject) {
        setToOneTarget("eipTProject", eipTProject, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTProject getEipTProject() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTProject)readProperty("eipTProject");
    } 
    
    
}
